import { StyleSheet } from 'react-native';

import { Fonts } from '@/constants/theme';

export const indexStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  flex: {
    flex: 1,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 4,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitleWrap: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 26,
    lineHeight: 32,
    fontFamily: Fonts.rounded,
    fontWeight: '600',
    letterSpacing: -0.5,
  },
  headerSubtitle: {
    marginTop: 1,
    fontSize: 12,
    fontFamily: Fonts.sans,
    letterSpacing: 0.1,
  },
  warningBox: {
    marginHorizontal: 18,
    marginTop: 10,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  warningText: {
    fontSize: 13,
    fontFamily: Fonts.sans,
  },
  searchWrap: {
    marginHorizontal: 18,
    marginTop: 10,
    marginBottom: 6,
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
    fontFamily: Fonts.sans,
    padding: 0,
  },
  fabButton: {
    position: 'absolute',
    bottom: 80,
    alignSelf: 'center',
    width: 58,
    height: 58,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.22,
    shadowRadius: 14,
    elevation: 10,
  },
  menuOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  drawer: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: 280,
    borderRightWidth: 1,
    paddingTop: 56,
    paddingHorizontal: 16,
    gap: 8,
  },
  drawerTitle: {
    fontSize: 11,
    lineHeight: 16,
    fontFamily: Fonts.mono,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginBottom: 4,
    opacity: 0.6,
  },
  drawerItem: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 11,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  drawerItemText: {
    fontSize: 15,
    lineHeight: 20,
    fontFamily: Fonts.rounded,
    fontWeight: '500',
  },
  drawerBlock: {
    borderTopWidth: 1,
    marginTop: 8,
    paddingTop: 12,
    gap: 8,
  },
  drawerBlockTitle: {
    fontSize: 11,
    lineHeight: 16,
    fontFamily: Fonts.mono,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    opacity: 0.6,
  },
  drawerThemeActionTextWrap: {
    flex: 1,
  },
  drawerThemeActionSubtext: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: Fonts.sans,
  },
});
