import { StyleSheet } from 'react-native';

import { Fonts } from '@/constants/theme';

export const recipeEditorStyles = StyleSheet.create({
  safeArea: { flex: 1 },
  flex: { flex: 1 },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 4,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.10,
    shadowRadius: 4,
    elevation: 2,
  },
  headerTextWrap: { flex: 1 },
  headerLabel: {
    fontSize: 11,
    lineHeight: 14,
    fontFamily: Fonts.mono,
    letterSpacing: 1.4,
    textTransform: 'uppercase',
  },
  scrollContent: {
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 80,
    gap: 16,
  },
  titleInput: {
    fontSize: 28,
    lineHeight: 34,
    fontFamily: Fonts.rounded,
    fontWeight: '600',
    letterSpacing: -0.5,
    padding: 0,
  },
  metaRow: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  metaPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  metaLabel: {
    fontSize: 12,
    fontFamily: Fonts.sans,
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  metaInput: {
    fontSize: 15,
    fontFamily: Fonts.rounded,
    fontWeight: '600',
    minWidth: 32,
    padding: 0,
    textAlign: 'center',
  },
  timelinePlaceholder: {
    marginTop: 8,
    paddingVertical: 36,
    paddingHorizontal: 24,
    borderRadius: 16,
    alignItems: 'center',
    gap: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  placeholderTitle: {
    fontSize: 15,
    fontFamily: Fonts.rounded,
    fontWeight: '600',
  },
  placeholderText: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: Fonts.sans,
    textAlign: 'center',
  },
  notFound: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
    padding: 24,
  },
  notFoundText: {
    fontSize: 14,
    fontFamily: Fonts.sans,
  },
  backButton: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 12,
  },
  backButtonText: {
    fontSize: 14,
    fontFamily: Fonts.rounded,
    fontWeight: '600',
  },
  ghost: {
    position: 'absolute',
    top: 0,
    left: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.30,
    shadowRadius: 12,
    elevation: 12,
  },
  ghostLabel: {
    fontSize: 13,
    fontFamily: Fonts.rounded,
    fontWeight: '600',
    color: '#fff',
  },
});
